# Generated by Django 5.2.5 on 2025-12-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='margen_ganancia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_critico',
            field=models.IntegerField(default=0),
        ),
    ]
