# Generated by Django 5.2.5 on 2025-11-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='rut',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
