# Generated by Django 5.2.8 on 2025-12-10 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_clientes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles_pedidos',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='main.producto'),
        ),
    ]
