# Generated by Django 5.2.8 on 2025-11-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20251116_0840'),
    ]

    operations = [
    ]
