# Generated by Django 5.2.8 on 2025-12-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_detalles_pedidos_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='margen_ganancia',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_unitario',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_critico',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
