# Generated by Django 5.2.5 on 2025-11-30 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_clientes_rut'),
        ('main', '0005_add_fecha_termino'),
    ]

    operations = [
    ]
