# Generated by Django 5.2.8 on 2025-12-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_producto_cantidad_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='margen_ganancia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_unitario',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_critico',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
