# Generated by Django 5.2.8 on 2025-12-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_producto_margen_ganancia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='margen_ganancia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
