# Generated by Django 5.2.8 on 2025-12-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_producto_margen_ganancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
