# Generated by Django 5.2.8 on 2025-12-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_clientes_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='precio_total',
        ),
        migrations.AlterField(
            model_name='detalles_pedidos',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(default='Pendiente de manufacturar', max_length=50),
        ),
    ]
